server:
  port: 5002
spring:
  application:
    name: sardine-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.116.169:3306/tripper?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  rabbitmq:
    host: 47.97.116.169
    username: admin
    password: admin
    virtual-host: sardine
    publisher-confirms: true        # 开启Confirm确认机制
    publisher-returns: true         # 开启Return确认机制
    template:
      mandatory: true               # 消费者在消息没有被路由到合适的队列下会被return监听，不会自动删除
    listener:
      simple:
        acknowledge-mode: manual    # 消费端手动ACK
        retry:
          enabled: true             # 是否支持重试
  redis:
    host: 47.97.116.169
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5000/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
sardine:
  jwt:
    secret: tripper@login&admin)secret^/
    pubKeyPath: D:\tripper-rsa\rsa.pub
    priKeyPath: D:\tripper-rsa\rsa.pri
    expire: 30  # 过期时间30分钟
    cookieName: SarineToken
ribbon:
  ConnectTimeout: 1000            # ribbon连接超时时长
  ReadTimeout: 1000               # ribbon读取超时时长
  MaxAutoRetries: 0               # 当前服务重试次数
  MaxAutoRetriesNextServer: 0     # 切换服务重试次数
  MaxTotalConnections: 500        # 最大连接数
